blank_issues_enabled: false

contact_links:
  - name: ğŸ“–  Read the docs
    url:  https://open-inflation.github.io/pyaterochka_api/quick_start.html
    about: Start here for â€œhow-toâ€ questions.
  - name: ğŸ’¬  Discord server (Discussions)
    url:  https://discord.gg/UnJnGHNbBp
    about: General Q&A and community support.
